### PR TITLE
App shutdown/john

### PR DESCRIPTION
**Pull request by heraldOfMechanus**
Wrote the shutdown() method and injected the 'app' dependency such that the Welcome screen (and any future screens) can potentially close the processes in a graceful and slick manner.

### CODE REVIEW

**Comment by heraldOfMechanus** [comment]
There are two commits with the same name because I removed an annoying-looking space in the second iteration of AppState. I only noticed it after I already committed once in IntelliJ.

**Comment by wsingleton** [comment]
Let's make the shutdown method static so the AppState object does not need to be passed around.

**Comment by heraldOfMechanus** [comment]
#9 Making the shutdown() method Static was surprisingly easy. I thought most of this kind of stuff needed to be injected
This must just be the power of the static keyword.

**Comment by wsingleton** [comment]
It is only acceptable because this is a console-based application that can only be leveraged by one user at a time. When we convert this into a web application, our startup and shutdown logic will be completely different.

**Comment by wsingleton** [comment]
looks good. Great work, @heraldOfMechanus!

**Comment by heraldOfMechanus** [comment]
Thank you kindly. I knew this was an easy one so I had to get it while it was hot before someone snatched it
Cody and a couple others were helping me this morning to fix this problem on my P0 >->

The static keyword was definitely something I overlooked because when you're in AppState, you start thinking things like "I can inject anything!"

**Pull request merged**
